### ISSUE TITLE
Test in master fails probably due to wheel package update

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#102]
We have to update the environment.yml for this

**Comment by treerink** [comment]
I think this might be the correct one now:
 wheel 0.30.0 py27h2bc6bb2_
So replace in environment.yml:
- wheel=0.30.0=py_1
by
- wheel=0.30.0=py27h2bc6bb2_1

**Comment by treerink** [comment]
Automatic tests are succesful again. The fix for the wheel version dependence indeed solved the issue.
Closing.

**Comment by goord** [comment]
Nice work!
