### ISSUE TITLE
Inconsistency for tos in atmosphere realm (currently it has been named tso).

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#112]
If in the taskloader variables are encountered which occur in both the nemopar.json and ifpar.json it has to be distinguished which of both has to be selected. Currently it is inpossible to handle this situation, whereas this doe occur in the data request: tos is an example of this.

**Comment by treerink** [comment]
At line 24 in ifspar.json "target": "tso" has to be changed in "target": "tos" after the code fix.

**Comment by goord** [comment]
rev. 123c147191311b2d2de8d975aa7b05339812a74a
