### ISSUE TITLE
First time step of the month

### ISSUE THREAD

**Issue by goord** [goord/ece2cmor3#12]
The 0h output of the previous month for instantaneous fields should be included in time averages

**Comment by klauswyser** [comment]
As a first step to solve this problem I have created a [new grib_filter filter file](https://github.com/goord/ece2cmor3/files/844008/split_3h_6h.txt)
that saves the first timestep of a month at the end of the previous month and at the start of the next month. And of course it splits 3-hourly and 6-hourly data in 2 files.

For fluxes we need  to include the first timestep from the next month, but for instantaneous fields we can skip it. This can be easily achieved in the post-processing step with cdo simply add `-seldate,$date1,$date2` before computing time averages where date1 and date2 are different for fluxes and for instantaneous fields (e.g. 1990-01-01T00:00:00,1990-01-31T23:59:00 for instantaneous fields, and 1990-01-01T00:00:01,1990-02-01T00:00:00 for fluxes)


[split_3h_6h.txt](https://github.com/goord/ece2cmor3/files/844008/split_3h_6h.txt)
