### ISSUE TITLE
how to generate varlist.json for a given MIP?

### ISSUE THREAD

**Issue by etiennesky** [goord/ece2cmor3#122]
Hi, at BSC we have managed to install the drq package and generate the .xls files for various MIPs.
What doesn't seem clear to me is how to generate the varlist.json file for each MIP? The drq2json.py file no longer exists, and I suspect it is not up to date.
@goord @treerink @pabretonniere 
Thanks!

**Comment by goord** [comment]
Hi Etienne, it is no longer necessary to convert to json anymore, ece2cmor3 should accept the excel file produced by the drq tool as is.

**Comment by treerink** [comment]
And from within the ece2cmor/ece2c,or/scripts/ directory, you can run in one go the drq and the checkvars.py script, e.g.:
./determine-missing-variables.sh ScenarioMIP historical 1 1
the arguments are respectively MIP, experiment, tier priority.
(I will update the ec-earth portal soon for examples etc.)

**Comment by etiennesky** [comment]
Hi guys, thanks for the information. I think the ec-earth wiki doc needs to be a bit more specific on this topic. I didn't understand both those things (can use excel file and determine-missing-variables.sh script) from the wiki docs.

**Comment by etiennesky** [comment]
Another question before I close this thread: how can we generate ourselves a custom list of variables to output? Would it be fine to create the .xlsx files from drq and then edit them manually?

**Comment by etiennesky** [comment]
or would it be simpler and smaller to write the varlist.json?

**Comment by goord** [comment]
One the one hand excel files are easier to edit by hands, on the other hand json files are easier to diff by machine, so that's up to you. I would go for the excel files I think.

**Comment by etiennesky** [comment]
Great thanks! I guess the old drq2json.py script can still be used to generate a proper .json file from excel tables (after saving them as .csv files)?
