### ISSUE TITLE
Add Thickness of Soil Layers to ece2cmor3

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#126]
Add Thickness of Soil Layers to ece2cmor3: Efx slthick longitude latitude sdepth	
Available in IFS: independent of lon, lat. 
Top soil layer: 0-7 cm, Soil layer 2: 7-28 cm, Soil layer 3: 28-100 cm, Soil layer 4: 100-289 cm
http://clipc-services.ceda.ac.uk/dreq/u/7124901e-c7b6-11e6-bb2a-ac72891c3257.html

**Comment by goord** [comment]
See issue #143
