### ISSUE TITLE
6hrPlevPt vars wrongly defined being overwritten

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#130]
Hi all,

I have seen that the 6hrPlevPt set of variabile in the PRIMAVERA branch is written as:

``` 
 "6hrPlevPt": [
        "hus27",
        "huss",
        "mrlsl",
        "mrsos",
        "psl",
        "sfcWind",
        "snw",
        "ta27",
        "tas",
        "ts",
        "tsl",
        "uas",
        "vas",
        "vortmean",
        "zg27",
        "hus7h",
        "ta7h",
        "va7h",
        "ua7h",
        "zg7h"
    ],
```
Looking at the output, clearly there is only one file each for zg and ta, meaning that the two 27 and 7h have been overwritten.  I guess this means that 6hrPlevPt is wrongly defined in varlist.json. Can someone confirm this?
Thanks a lot

**Comment by goord** [comment]
Hi Paolo, it is unlikely that the files are overwritten because the variables are named differently. Can you check that both zg27, zg7h, ta27 and ta7h are in the table CMIP6_6hrPlevPt.json (see the resources/tables directory)? Does ece2cmor3 complain about them when it constructs the tasks in the beginning?

**Comment by oloapinivad** [comment]
Hi,
variables names are different, but they are somehow both directed to "zg" and "ta", since I get in the directory tree: 
````
[pdavini0@r000u08l03 6hrPlevPt]$ ls
hus  huss  sfcWind  snw  ta  tas  ua  uas  va  vas  vortmean  zg
````

Inside zg and ta I have a single file with 27 levels, so that only the ??27 is stored. 
I can find both the ??27 and ??7h in CMIP6_6hrPlevPt.json. I wondering if this depends on the ifspar.json where 

````
{
        "source": "129.128",
        "convert": "pot2alt",
        "target": [
          "zg",
          "zg7h",
          "zg23",
          "zg27",
          "zg1000",
          "orog"
        ]
    },
````

I cannot find any evident problem in the log file...

**Comment by oloapinivad** [comment]
I further look at the output while the code was running and I can confirm that the ece2cmor3 is firstly doing the 7h vars and then the 27 ones, but since they both point to zg/ta its ends up overwriting the latter on the former. I am not sure if this is a problem in how I specified the varlist.json or if this should be handled somehow by ece2cmor3.

**Comment by oloapinivad** [comment]
deprecated following #148
