### ISSUE TITLE
update ifspar.json and nemopar.json from PRIMAVERA branch to master? [question]

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#140]
Hi all,

I found out that inside the PRIMAVERA branch both nemopar.json and ifspar.json include more variables than in the master branch. Using the PRIMAVERA branch version provides much more cmorized data, so every time I pull some changes I must replace those files. 

Since the master is the officially maintained branch right now, would it be possibile to update the two files also in the master branch? Or this is going to cause some problem in view of CMIP6?

Thanks a lot

**Comment by goord** [comment]
Hi Paolo, what should the master varlist.json contain you think? All the possible variables for all MIPs that can be processed by ece2cmor3 perhaps...


btw you can run ece2cmor.py with a different varlist than the default included one by using the option --vars=<path-to-your-varlist-file>

For the upcoming cmip6 experiments, it is possible to generate these variable lists with the dreq tool, but not for primavera unfortunately.

**Comment by oloapinivad** [comment]
Hi @goord, I am not talking about the varlist.json, which clearly should be set up by each user (and this is actually what I am doing).

I am talking about ifspar.json and nemopar.json, which should be universal, don't they? Perhaps I am not understanding how the tool works, but these are converting the codes/varnames from NEMO/IFS to the cmor names. Do I had missed something?

**Comment by goord** [comment]
Sorry you are absolutely right.

But I think the problem is that the parameter tables in the master branch are too much up-to-date for primavera cmor jobs no?

**Comment by oloapinivad** [comment]
Hard to tell, the situation is quite confusing at least for me.

I am using the parameter tables (if this is not the right name for ifspar.json and nemopar.json please correct me) from the PRIMAVERA branch with the master branch, and this is working fine (but for now only with the CMIP6 tables). 

Using the parameter tables from the master branch lead to much less variables especially for the ocean: if you look at the number of lines you will see that on the PRIMAVERA branch nemopar.json has much more variables available. 

So my idea was to extend the range of variables covered updating the parameter tables. But I must say that from here I am not seeing the full picture of the cmorization, so that mine was a simple suggestion. I don't know if this is going to affect someone else work.

**Comment by goord** [comment]
Hi Paolo, I think I know what happened: @pabretonniere added all those ocean variables in the primavera branch but we never merged this to the master...

**Comment by treerink** [comment]
Hmmm, so I am curious then to see how many that are?

**Comment by oloapinivad** [comment]
@treerink in the PRIMAVERA branch in nemopar.json there are around 60 vars vs.  about 40 for the master branch.

**Comment by treerink** [comment]
I found that  11 of the nemo variables in the nemopar.json in the primavera branch are obsolete against the current cmor tables.

I copied the nemopar.json from the primavera branch over the nemopar.json in the master branch and run the check-for-obsolete-cmor-variables-in-json-file.py script by:
```shell
cd ${HOME}/cmorize/ece2cmor3/; python setup.py install; cd -;
./check-for-obsolete-cmor-variables-in-json-file.py
```
This results in:
```shell
INFO:__main__:Obsolete target found in ../resources/nemopar.json: isiitdsnthick
INFO:__main__:Obsolete target found in ../resources/nemopar.json: hfsithermds2d
INFO:__main__:Obsolete target found in ../resources/nemopar.json: precip
INFO:__main__:Obsolete target found in ../resources/nemopar.json: u2o
INFO:__main__:Obsolete target found in ../resources/nemopar.json: uto
INFO:__main__:Obsolete target found in ../resources/nemopar.json: tso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: uso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: v2o
INFO:__main__:Obsolete target found in ../resources/nemopar.json: vto
INFO:__main__:Obsolete target found in ../resources/nemopar.json: vso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: w2o
```
while currently for the nemopar.json in the master branch there are no obsolete nemo variables found.

This leaves about 9 variables. However, finished primavera runs are possibly based on variable names in the older cmor tables as in the nemopar.json in the primavera branch and the tables there.

**Comment by treerink** [comment]
Actually we are planning to add all the non-dummy nemo variables from the so called Shaconemo "ping files" in the nemopar.json in the master branch, which are about 250 nemo variables.

**Comment by treerink** [comment]
I found that  11 of the nemo variables in the nemopar.json in the primavera branch are obsolete against the current cmor tables.


I copied the nemopar.json from the primavera branch over the nemopar.json in the master branch and run the check-for-obsolete-cmor-variables-in-json-file.py script by:
cd ${HOME}/cmorize/ece2cmor3/; python setup.py install; cd -;
./check-for-obsolete-cmor-variables-in-json-file.py 
This results in:
INFO:__main__:Obsolete target found in ../resources/nemopar.json: isiitdsnthick
INFO:__main__:Obsolete target found in ../resources/nemopar.json: hfsithermds2d
INFO:__main__:Obsolete target found in ../resources/nemopar.json: precip
INFO:__main__:Obsolete target found in ../resources/nemopar.json: u2o
INFO:__main__:Obsolete target found in ../resources/nemopar.json: uto
INFO:__main__:Obsolete target found in ../resources/nemopar.json: tso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: uso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: v2o
INFO:__main__:Obsolete target found in ../resources/nemopar.json: vto
INFO:__main__:Obsolete target found in ../resources/nemopar.json: vso
INFO:__main__:Obsolete target found in ../resources/nemopar.json: w2o
while currently for the nemopar.json in the master branch there are no obsolete nemo variables found.

**Comment by treerink** [comment]
To make it easier to use the master branch for primavera output we will add the featurte #142

**Comment by oloapinivad** [comment]
I am pretty confused. As @treerink pointed out, some of the vars are obsolete. Moreover, many vars in the varlist.json and nemopar.json, which I took from the latest commit in the PRIMAVERA branch are not present in the PRIMAVERA request that I found on Jon Seddon's archive at https://github.com/jonseddon/cmip6-cmor-tables/tree/master/etc and in the corresponding tables.

Indeed I am obtaining these errors: 
`````
ERROR:ece2cmor3.taskloader:The siprn variable does not appear in the CMOR table file CMIP6_SImon.json
ERROR:ece2cmor3.taskloader:The precip variable does not appear in the CMOR table file CMIP6_Omon.json
ERROR:ece2cmor3.taskloader:The sistrxdtop variable does not appear in the CMOR table file CMIP6_SIday.json
ERROR:ece2cmor3.taskloader:The sistrydtop variable does not appear in the CMOR table file CMIP6_SIday.json
ERROR:ece2cmor3.taskloader:The orog variable does not appear in the CMOR table file CMIP6_AERmon.json
ERROR:ece2cmor3.taskloader:The psl variable does not appear in the CMOR table file CMIP6_E3hrPt.json
ERROR:ece2cmor3.taskloader:The snw variable does not appear in the CMOR table file CMIP6_Eday.json
ERROR:ece2cmor3.taskloader:The mrro variable does not appear in the CMOR table file CMIP6_Eday.json
``````

For example, it seems that **siprn** does not exists. 

@pabretonniere @jmrgonza @klauswyser, since you all worked with PRIMAVERA output would you mind to tell me where I can found a varlist.json and nemopar.json that is updated against the PRIMAVERA request and tables? More generally, do they exist? 
Thanks a lot for any suggestion.

**Comment by oloapinivad** [comment]
Following #142 I think I can close this. We will need an issue on PRIMAVERA Jon Seddon's table.
