### ISSUE TITLE
Add the option to ece2cmor to specify the nemopar.json file. Same for the ifspar.json.

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#142]
Adding two arguments to ece2cmor:
1. The nemopar.json file
2. The ifspar.json file

Note that the argument option
--tabid PREFIX                         Cmorization table prefix string (default: CMIP6)
already exits.

Therefore the addition of this two arguments will make it possible to use from the master branch your CMOR table with your nemopar.json. This for example allows to use the master branch for cmorization of primavera output, which was created based on an older request matching with older CMOR tables.

So it should work somehow like e.g.: 
ece2cmor --nemopar ./ece2cmor3/resources/primavera-nemopar.json

**Comment by oloapinivad** [comment]
Thanks a lot, this will simplify the thing.

**Comment by oloapinivad** [comment]
Great thanks

**Comment by oloapinivad** [comment]
Hi @goord 

sorry to bother on this, but I am testing the new option and I am not sure is working as planned.
I have specified my own nemopar.json (which is mainly the one coming from the PRIMAVERA branch) as ` --nemopar nemopar.json` 
This file include the `sivol` specification, which is missing in the default one:

````
 {
        "source": "sivol",
        "grid": "icemod",
        "target": "sivol"
    },
````

However, when running ece2cmor3 the program is not finding the variable in the parameter table (on the other hand, it is not giving any error). Could it be possible that is reading the parameter table but ignoring it?


`````
/marconi_work/Pra13_3311/ecearth3/PRIMAVERA/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py /marconi_scratch/userexternal/pdavini0/tmp_cmor/qctr_21144/tmp_1950_1/linkdata 1950-01-01 --exp qctr --conf /marconi_scratch/userexternal/pdavini0/tmp_cmor/qctr_21144/tmp_1950_1/cmorized/CMIP6/metadata-qctr-leg000.json --vars /marconi/home/userexternal/pdavini0/ecearth3/ece3-postproc/ece2cmor3_support/varlist/varlist-short.json --npp 1 --tmpdir /marconi_scratch/userexternal/pdavini0/tmp_cmor/qctr_21144/tmp_1950_1/cmorized/CMIP6 --nemopar /marconi/home/userexternal/pdavini0/ecearth3/ece3-postproc/ece2cmor3_support/paramtable/nemopar.json --tabid CMIP6 --tabdir /marconi_work/Pra13_3311/ecearth3/PRIMAVERA/cmorization/cmip6-cmor-tables/Tables --mode append --oce
INFO:ece2cmor3.taskloader:Found 4 cmor target variables in input variable list.
ERROR:ece2cmor3.taskloader:Could not find parameter table entry for sivol in table SImon...skipping variable. This variable is identified missing
INFO:ece2cmor3.taskloader:Created 1 ece2cmor tasks from input variable list.
INFO:ece2cmor3.ece2cmorlib:Selected 1 NEMO tasks from 1 input tasks
INFO:ece2cmor3.nemo2cmor:Creating NEMO grids in CMOR...
``````
 
Thanks,
Paolo

**Comment by goord** [comment]
Hi Paolo, I hope I fixed the bug in 4a76ca8a2b4070d694b808ade702cc7e6b0dfd94, can you please try once more?

**Comment by goord** [comment]
I'm sorry I made a mistake, fixed it in the latest commit

**Comment by goord** [comment]
You can pass ifspar if you want for an ocean job, it will just not be used

**Comment by oloapinivad** [comment]
Hi @goord, tested it right now, it is working now. 
Thanks!
P

**Comment by treerink** [comment]
So I close it.
