### ISSUE TITLE
PRIMAVERA tables and filtering

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#145]
Hi all,

Thanks to your help I am able to make work PRIMAVERA tables  with master branch, which means that the most of the required variables can be correctly obtained (if the correct variables and parameters tables are used)

However, at the moment of the filtering I am getting this error for a few variables:

``````
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 100, level 40. Dismissing task hus23 in table Primday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 100, level 40. Dismissing task ta23 in table Primday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 100, level 40. Dismissing task ua23 in table Primday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 100, level 40. Dismissing task va23 in table Primday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 100, level 40. Dismissing task wap23 in table Primday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 100, level 40. Dismissing task zg23 in table Primday
``````

As long as I understand the filtering is not finding in the first file the pressure level 40 for hus,va,zg etc. However, the pressure level a 40 Pa is there, as all the other 44 pressure levels shown by: 

````
[pdavini0@r000u07l02 IFS]$ cdo showlevel -selcode,129 ICMSHqctr+194912
cdo showlevel: Started child process "selcode,129 ICMSHqctr+194912 (pipe1.1)".
 100000 97500 95000 92500 90000 87500 85000 82500 80000 77500 75000 74000 70000 65000 62000 60000 55000 50000 45000 40000 37500 35000 30000 25000 24500 22500 20000 17500 15000 12500 10000 9000 7000 5000 3000 2000 1000 900 700 500 300 200 100 40
````

So I am thinking there is an issue in the way the filtering operates on those vars, perhaps we need to fix something in the Primavera tables? 
Thanks for any hint

**Comment by goord** [comment]
I know the problem: 40 Pa is too low for the standard encoding in GRIB so it uses a different level type, which I didn't account for in the filtering. I will fix this asap.

**Comment by goord** [comment]
Should be fixed after rev. f7ffe034eb513b5f62416d1bd3e3f883440232fc

**Comment by oloapinivad** [comment]
Great! I am testing it right now and it's working like a charm. I can close this.
