### ISSUE TITLE
pressure levels vars: do we need to specify plev in the name of the var? 

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#148]
Hi all, 

There are some variables that sometimes can be defined on several pressure levels at the same time. For example, I found out we can have zonal wind on plev7h, plev27 levels, etc... according to the table here https://earthsystemcog.org/site_media/projects/wip/CMIP6_pressure_levels.pdf we can have plenty of combinations. 

PRIMAVERA tables are working in the way to save in the name of variables also the plev used, so you can find files as **ua23_Primday_EC-Earth3-HR_piControl_r1i1p1f1_gr_19500101-19500131.nc** produced in this way.

Conversely, CMIP6 tables are (more correctly?) storing the variables name, so that you can have a file named **ua_day_EC-Earth3-HR_piControl_r1i1p1f1_gr_19500101-19500131.nc**

I am realizing that this was the issue I was experiencing in #130, where I was having both zg23 and zg7h saved in the same table (6hrPlevPt) in a CMIP6 varlist, leading to the overwriting of the second on the former (the two of them will be named simply **zg_6hrPlevPt_EC-Earth3-HR_piControl_r1i1p1f1_gr_195001010000-195001311800.nc**).

A few question arises:
1. Why this different behaviour? Were you aware of it?
2. I think that the reasonable scheme is the CMIP6 one. Any opinions?
3. For which reason someone would like to save both plev23 and plev7h for the same var at the same frequency? I am surprised on the design of these varlist.json...

thanks a lot for the usual help!
Best,
Paolo

**Comment by goord** [comment]
Hi @oloapinivad, does this also occur when you use the CMIP6 tables from Jon Seddon? Because he uses an older version of the CMIP6 tables.

**Comment by oloapinivad** [comment]
Hi @goord, yes.
I am using the --tabdir flag in order to point to the Jon Seddon version (01.00.13). 
Perhaps something went wrong because Jon Seddon is still updating its CMIP tables (now I see on its github version is 01.00.23)?

**Comment by treerink** [comment]
Hi, just mentioning it:
The ece2cmor3 master branch has been updated for the cmor 3.3.2 library (which is compatable with drq 01.00.23) and I just also updated the nested cmor tables. But the cmor 3.3.2 library requires recreating the ece2cmor environment:

````shell
conda env remove --name ece2cmor3
conda env create -f environment.yml
````

**Comment by goord** [comment]
Hi Paolo, FYI the included varlist.json is supposed to be a list of all variables ece2cmor3 can actually produce, not necessarily an output request that makes sense.

I agree with you it doesn't make sense to output a variables on various pressure level sets in the same table, and apparently the CMOR people also believe this, since they save the data under the same file name.

Hence I would advice you to remove the ua7h,... variables from the varlist so they don't cause the extended pressure level set data to be overwritten.

**Comment by oloapinivad** [comment]
Hi @goord, I agree. 
My concerns were coming from the fact that I took the varlist.json from the PRIMAVERA branch, so I was expecting that this was the right variable list to use. I guess this is not the case. I will do as you suggest. 

However, the whole PRIMAVERA thing is a mess - and this is not your fault. 
For example, variables ua850 and va850 in the E3hrPt,  which are in the variable request ([here](https://prima-dm.ceda.ac.uk/variable_requests/?cmor_name=ua850&table_name=&long_name=&units=&frequency=&standard_name=&var_name=&cell_methods=&cell_measures=&dimensions=&positive=&uid=&variable_type=&modeling_realm=)) does not exist in the correspondent CMIP6_E3hrPt.json. 

@treerink I am trying the new release with cmor 3.3.2 library - thanks for the hint of reinstalling the environment - there are a few issues for now, I will open an issue if they persist...

**Comment by oloapinivad** [comment]
I see the problem. 
Yes it is a good idea to open one on the Jon Seddon's table. Closing this one.
