### ISSUE TITLE
Update the cmor library version to cmor 3.3.2 for OS X

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#152]
Related to #149 now the cmor 3.3.2 has also become available for OS X.

So for Mac OS X the cmor dependency should be updated to:
cmor-3.3.2.npy1.13-py27_0 depends on cdms2, gcc, hdf5 >=1.10, libnetcdf >=4.4, numpy 1.13.*, ossuuid >=1.6, python >=2.7,<2.8.0a0, udunits2

**Comment by treerink** [comment]
With the just added env-osx-64-cmor-release-3.3.2.yml (in which all the dependencies have been updated - roughly for the hdf5 1.10 & netcdf 4.4 combination, and cdo - eccodes combination)  it was possible to create successfully the environment based on the cmor 3.3.2 library.

Unfortunately I get e.g. an error when using the checkvars.py script:
````script
  File "./checkvars.py", line 8, in <module>
    from ece2cmor3 import ece2cmorlib,taskloader,cmor_source,cmor_utils
  File "/Users/reerink/anaconda2/envs/ece2cmor3-cmor-release-3.3.2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 1, in <module>
    import cmor
  File "/Users/reerink/anaconda2/envs/ece2cmor3-cmor-release-3.3.2/lib/python2.7/site-packages/cmor/__init__.py", line 7, in <module>
    from cmor_const import *
  File "/Users/reerink/anaconda2/envs/ece2cmor3-cmor-release-3.3.2/lib/python2.7/site-packages/cmor/cmor_const.py", line 1, in <module>
    import _cmor
ImportError: dlopen(/Users/reerink/anaconda2/envs/ece2cmor3-cmor-release-3.3.2/lib/python2.7/site-packages/cmor/_cmor.so, 2): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /Users/reerink/anaconda2/envs/ece2cmor3-cmor-release-3.3.2/lib/python2.7/site-packages/cmor/_cmor.so
  Reason: Incompatible library version: _cmor.so requires version 10.0.0 or later, but libcurl.4.dylib provides version 9.0.0
````
 Have not looked further into this yet.

**Comment by goord** [comment]
Apparently the curl library is outdated on your system, but cmor doesn't list it correctly in anaconda so you don't notice it when creating the environment. Can you either update the curl conda version in the osx environment or maybe remove it from the list and see what happens?

**Comment by treerink** [comment]
Removing curl seems to work (at least for checkvars.py)

**Comment by treerink** [comment]
Well it finds out itself that it needs (currently) curl 7.59 (instead of 7.55 as specified before).

**Comment by treerink** [comment]
Issue solved.

As before on OS X in order to be able to run checkvars.py and similar applications: line 4 in grib_file.py has to be commented:
`````script
#import gribapi
`````
However the update to cmor 3.3.2 itself is fine now for OS X
So closing this issue.
