### ISSUE TITLE
Running a simple PRIMAVERA example - nothing happens

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#16]
I try to run `examples/primavera/prim_atm_6hr.py` with a very simple variablelist:
<pre>
{
    "Amon": [
        "tas",
        "ts"
    ]
}
</pre>
Everything seems to go well, no error message, but nothing happens -  I don't get any cmorized output. Here is the log:
<pre>
INFO:ifs2cmor:Executing 0 IFS tasks...
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
</pre>
What am I missing?

**Comment by goord** [comment]
Klaus is that the full log or is it still complaining about the variables in the tables?

**Comment by klauswyser** [comment]
This is the full log. I have updated ece2cmor3 from the git repository this morning, and also added the submodules to get the CMOR tables, it's all in place now.

**Comment by goord** [comment]
Unfortunately I cannot reproduce it, on my system the varlist you posted works as expected. Can you put print statements at the beginning and the end of the filter_tasks function in ifs2cmor.py (line 128) to see how many tasks are passed to it, and how many it filters out? Otherwise you can step through the code by running the script with 'pdb', which works just like gdb.

**Comment by goord** [comment]
It may also be useful to put some print statements in the main script, to see whether the jsonloader indeed converts your variable list into tasks.

**Comment by goord** [comment]
Klaus I added extra logging to the json parsing code in aea5e2ad56728ad1e22cd9921e225f6eaf958ae1, which may help us to pin the bug...

**Comment by klauswyser** [comment]
I updated ece2cmor3 and now get some extra output:
<pre>
INFO:jsonloader:Found 2 cmor target variables in input variable list.
INFO:jsonloader:Created 2 ece2cmor tasks from input variable list.
INFO:ifs2cmor:Executing 0 IFS tasks...
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
</pre>
Some tasks are created, but somehow they don't end up as IFS tasks.

**Comment by goord** [comment]
Ok I added more logging and restructured the filter_tasks a bit, you might want to retry after checking out rev. 53746ddf4e5abf45f67b24807dcf851db9d936bb

**Comment by klauswyser** [comment]
Now I get:
<pre>
INFO:jsonloader:Found 2 cmor target variables in input variable list.
INFO:jsonloader:Created 2 ece2cmor tasks from input variable list.
INFO:ifs2cmor:Inspecting 0 tasks.
INFO:ifs2cmor:Validated 0 tasks for processing.
INFO:ifs2cmor:Executing 0 IFS tasks...
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
</pre>
I tried running with pdb but don't know where to put breakpoints. At l.128 in ifs2cmor varibale task is already empty.

Sine you can run this simple example but I cannot I wonder if something in the whole process is overly sensitive to the exact version of python or any of the modules. Would it make sense to compare our setups?

**Comment by goord** [comment]
I suspect our python versions differ. You were also the only one suffering from the temp_dir_ problem. I suspect your python version strictly requires all global module variables to be declared with 'global' inside a function. Can you try once more with the latest commit I did, and can you also share your version of python?

If my theory is correct, I will add the global declarations everywhere, because it is prescribed by the syntax.

**Comment by goord** [comment]
BTW does the test suite run on your system? To run it, type ```nosetests -v``` in the cloned repo

**Comment by klauswyser** [comment]
The latest output shown above (https://github.com/goord/ece2cmor3/issues/16#issuecomment-286780119) is with the latest version, the behaviour hasn't changed.

My python version is 2.7.12, and here are my installed packages (CMOR is 3.2.2!):
<pre>
appdirs==1.4.3
cdo==1.3.2
CMOR==3.2
f90nml==0.20
netCDF4==1.2.7
nose==1.3.7
numpy==1.11.3
packaging==16.8
pyparsing==2.2.0
python-dateutil==2.6.0
six==1.10.0
testfixtures==4.13.3
</pre>

Here are the results from `nosetests -v`: [nosetest_triolith.txt](https://github.com/goord/ece2cmor3/files/845309/nosetest_triolith.txt)

A few warnings, otherwise things seem to work OK.

**Comment by goord** [comment]
That seems to be the same configuration as mine. Sorry for the inconvenience, I added extensive logging this time...would it be possible to run your script once more and post the log? Thanks

**Comment by klauswyser** [comment]
@goord :+1:   The inconvenience must be on your side, I just update, run and don't understand why it's not working, while you try to troubleshoot my problems remotely which is not the easiest thing to do.

Here is the latest output, not much new:
<pre>
INFO:jsonloader:Found 2 cmor target variables in input variable list.
INFO:jsonloader:Created 2 ece2cmor tasks from input variable list.
INFO:ece2cmor:Selected 0 IFS tasks from 0 input tasks
INFO:ece2cmor:Extra info for bug#16: the given input tasks are...
INFO:ifs2cmor:Inspecting 0 tasks.
INFO:ifs2cmor:Validated 0 tasks for processing.
INFO:ifs2cmor:Executing 0 IFS tasks...
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
</pre>

**Comment by goord** [comment]
Ok, Klaus I think I found your problem: the prim_atm_6hr script **removes** all tasks that originate from 3-hourly output (see line 56 in the prim_atm_6hr.py), so it can be applied to the 6-hourly filtered output without error messages. Those variables you inserted are surface variables (3-hourly), so you can either comment out line 56, or apply prim_atm_3hr.py to your varlist. 

Maybe we should merge the scripts and distinguish between 3- and 6-hourly output variables with some command-line option...

**Comment by klauswyser** [comment]
@goord cudos! After commenting l.56 everything works fine and I get the output.

I don't understand all the details of the ece2cmor3 yet, but do you say that tasks are hardcoded to work on either 3-hourly or 6-hourly data? That may good enough for the first prototypes, but we have to make sure that the tool becomes flexible enough to process even model output that has been saved only every 6 hours. But that's something to keep an eye on in the future, so I close this issue now.

Thanks a lot for your great assistance and patience!
