### ISSUE TITLE
Remove or recycle obsolete IFS variables in ifspar.json

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#164]
Hi Gijs,

Checking with `./check-for-obsolete-cmor-variables-in-json-file.py` we still have some obsolete variables left:

`````script
Obsolete target found in:
../resources/ifspar.json: thetapv2
../resources/ifspar.json: wsgmax
../resources/ifspar.json: ua4
../resources/ifspar.json: ua7c
../resources/ifspar.json: ua200
../resources/ifspar.json: ua850
../resources/ifspar.json: va4
../resources/ifspar.json: va7c
../resources/ifspar.json: va200
../resources/ifspar.json: va850
../resources/ifspar.json: hus7c
../resources/ifspar.json: rv
../resources/ifspar.json: rsdtcs
../resources/ifspar.json: al
../resources/ifspar.json: rluscs
`````
It is straightforward to clean the `ifspar.json` but maybe you prefer to check whether this variables are renamed and we can recycle these items? Like for mrlsl -> mrsol in #156.

**Comment by goord** [comment]
Hi Thomas,
Ambiguities can only occur if a variable has been claimed by other components of EC-Earth such as mrsol. This can never be the case for the variables above, they are clearly pure atmospheric variables. Hence they must have been removed from the drq, or replaced by something that ece2cmor3 can produce as well. Therefore they are safe to remove from ifspar.json.

**Comment by treerink** [comment]
Ok removed in ba65d76
