### ISSUE TITLE
hardcoded information in primavera.json

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#18]
`primavera.json` contains information that describes where the output will be stored, and information that goes in the header of the cmorised netCDF files. SOme of this information is hardcoded (e.g. `outpath=/tmp/cmor3`)  and some infromation refers explicitely to KNMI (e.g. `further_info_url=http://furtherinfo.es-doc.org/CMIP6.KNMI.EC-Earth.historical`). This kind of information needs to be handled more flexible so other institutes can process their simulations.

**Comment by goord** [comment]
Hi Klaus, I agree with you on this, but the file primavera.json serves as input for the cmor3 library, and we have not much influence on the format (cmor3 checks strictly whether all fields are present). The file in the repo is just an example and other institutes are supposed to replace their information in it.

I propose that this json file becomes an input to the run scripts (just like varlist) such that you can keep your own version of it in the repo and run with that one. Also, in the ec-earth repo we may want to generate it with ecconf...

**Comment by klauswyser** [comment]
> I propose that this json file becomes an input to the run scripts (just like varlist) such that you can keep your own version of it in the repo and run with that one. Also, in the ec-earth repo we may want to generate it with ecconf...

That sounds like a good plan. It hasn't high priority though, so we can do it later.

BTW: there are many entries in the primavera.json file that should be discussed and agreed upon in the EC-EARTH community (e.g. license or contact information). At some point  we probabaly need to go through this file entry by entry.

**Comment by klauswyser** [comment]
See https://drive.google.com/open?id=16NTTxZM9l8B_tqLrG_zTJDGZYJr21dS7L3B-tGU2Wik and contribute to the discussion of metadata.
