### ISSUE TITLE
cdo shifttime is not used properly

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#19]
I noticed that the cdo command fro processing IFS output always contains `-shifttime,-${output_freq}hours`, e.g.
<pre>
Post-processing target tas [...] with cdo command -setgridtype,regular -monmean -shifttime,-6hours -selcode,167
</pre>
This is not correct for instantaneous fields such as temperature. I explain this with daily averages, but it works equally for monthly means.

The daily mean of an _instantaneous_ field (e.g. temperature) consists of the output at 00, 03, 06, ...18, 21. On the other hand, the daily mean of an _accumulated_ field (e.g. radiation) consists of the output at 03, 06, 09,..., 18, 21, 00+1day. The reason is that the accumulated field is saved at the end of the accumulation period (and with the corresponding timestamp), so the radiation at 03 is the accumulated radiation between 00 and 03. Therefore, the 00 timestep of the day is not needed for the daily average (it would contain hours 21-24 from the day before), but the 00 timestep of the next day is needed.

In the old ece2cmor tool I did this by shifting the timeaxis for accumulated fields before computing daily or monthly means. But only for accumulated, not instantaneous fields. This can be achieved by first adding the 00 timestep of the first day of a month to the monthly IFS output file (the last timestep from the previous month), and then apply `-selmon,$month` for instantaneous fields, and `-selmon,$month -shifttime,-${output_freq}hours` for accumulated fields.

Note: the new [grib_filter file](https://github.com/goord/ece2cmor3/files/844008/split_3h_6h.txt) that I presented in https://github.com/goord/ece2cmor3/issues/12#issuecomment-286693735 adds the first timestep of a month from the IFS output of the previous month when splitting 3-houlry and 6-hourly output.

**Comment by goord** [comment]
Hi Klaus, thanks for the explanation, I think this should definitely get priority. I will have a look at it this weekend.

**Comment by goord** [comment]
Fixed in rev. dc26c660e60cef0f14018d3d064ebe30029f1a93
