### ISSUE TITLE
time_bnds

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#22]
The time bounds are somewhat off.

Here an example of a file with monthly means (just 1 month processed):
`time_bnds =
  0, 30.875`
The month should extend to the end of the first month, i.e. 31 days. Otherwise we will have gaps in the timeline when stitching together two files.

And here an example of time_bnds from daily output: 
`time_bnds =
  -0.0625, 0.9375,
  0.9375, 1.9375,
  1.9375, 2.9375,
  2.9375, 3.9375,`
The time bounds don't start 00Z and end 24Z of each day but are off by 1.5 hours (=half of a 3-hour timestep)

**Comment by goord** [comment]
Commit nr 786d6ec94625e129dddf670a95cae631aaae6268

**Comment by klauswyser** [comment]
time_bnds for daily output is still not ok:

 time_bnds =
  14610, 14610.9375,
  14610.9375, 14611.9375,
  14611.9375, 14612.9375,
[...]
  14637.9375, 14638.9375,
  14638.9375, 14639.9375,
  14639.9375, 14641 ;

**Comment by goord** [comment]
Oops I only fixed it for the start and end times of the axis...

**Comment by goord** [comment]
This commit should have fixed it : f436688a45dc378d86723195f45bfe45a18b19f1
