### ISSUE TITLE
reference time

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#23]
What reference time should be set in the cmorized output? The reference time enters the time (and time_bnds) in the units, e.g. `days since 1990-01-01 00:00:00`

For CMIP5 the reference time was 1850-01-01T00:00:00, do we already know what it should be for CMIP6?  If it is not specified (yet) I suggest to set 1950-1-1 as the reference date for all PRIMAVERA experiments.

**Comment by goord** [comment]
Commit 9daee156c7c99450278656f6c122726f58470de3
