### ISSUE TITLE
ece2cmor claims that nemo output file already exists

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#31]
When processing NEMO output I get the error message

``! Error: Output file ( ./cmor/CMIP6/institute_idEC-Earth-3-HR/CMIP/historical/r1i1p1f1/Omon/tos/gr/v20170508/tos_Omon_EC-Earth-3-HR_historical_r1i1p1f1_gr_199001-199012.nc ) already exists,`` 

despite the fact that I the output directory cmor didn't even exist before starting processing.

**Comment by goord** [comment]
Klaus can you post the entire log output? I can't reproduce this problem on my system

**Comment by klauswyser** [comment]
Here we go: [ece2cmor3_20170604.txt](https://github.com/goord/ece2cmor3/files/1050629/ece2cmor3_20170604.txt)

**Comment by goord** [comment]
This is very strange, CMOR first reports it will create your output directory, and later it complains that the file already exists...

**Comment by goord** [comment]
O now I see it does the whole process twice...

**Comment by goord** [comment]
Klaus can you also post your varlist and ece2cmor3 command? It appears to perform the whole cmorization twice in your case, and I can't figure why it does so...

**Comment by klauswyser** [comment]
./ece2cmor.py --exp pr01 --vars varlist-klaus.json --conf highresSST-present_input.json --freq 6 -o tmp 1990-01-01

[varlist-klaus.json](https://github.com/goord/ece2cmor3/files/1063789/varlist-klaus.json.txt)

**Comment by klauswyser** [comment]
Finally, I could make the NEMO processing work, the problem was caused by the fact that I was using the primavera and not the master branch. After switching back to the master, the NEMO processing worked as expected. But now the IFS processing doesn't work any longer....

Closing this issue and open a new one.
