### ISSUE TITLE
metadata for highresSST-present experiment 

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#34]
Here is my take for a metadata file for the PRIMAVERA AMIP experiment: https://drive.google.com/open?id=0B-E865OyTp51MC1jeEQ3T0ZLMjQ

It works with cmor-3.2.3

**Comment by goord** [comment]
Hi Klaus, thanks for the info. I am redoing the cmorization of our PRIMAVERA amip run with this metadata now, and I encounter no problems whatsoever.

**Comment by klauswyser** [comment]
@goord : are you concatenating the cmorized IFS output in say yearly chunks, or do you leave them as monthly files? Once we do coupled runs, the ocean data will be in yearly files, although not mandatory it would be nice to have the IFS output in the same chunks.

**Comment by goord** [comment]
I am concatenating the monthly means. But daily and 3/6 hourly data can become several gb per file, so I am not sure whether it is convenient to chunk them...

**Comment by klauswyser** [comment]
Good point with the size of daily and sub-daily output files.

There will be daily output from the ocean in the yearly output file. Will this then be split into monthly files to be consistent with the atmosphere?

**Comment by goord** [comment]
I think this is automatic, because ece2cmor3 will only process a single month right? Even if you choose the 'append' mode in cmor, it will create new files for every month. I don't know if there is are settings in the cmor library to change this.

**Comment by klauswyser** [comment]
The NEMO output (even daily) comes in yearly files and they are not split into smaller chunks but retain one year in each cmorized file.

I haven't tested CMOR append mode yet, but recall that the old CMOR2 library could append to an existing file and  modify the filename accordingly. Maybe this feature doesn't exist any longer.

**Comment by goord** [comment]
Created a new issue for this: #35

**Comment by klauswyser** [comment]
Great, thanks! Closing this issue now.
