### ISSUE TITLE
Ocean mask

### ISSUE THREAD

**Issue by goord** [goord/ece2cmor3#38]
If we decide not to have missing values over land in NEMO for performance reasons, we should at least provide ece2cmor3 with a mask so that it can apply it during cmorization. This functionality will need to be implemented in the nemo2cmor module.

**Comment by klauswyser** [comment]
Do we need to mask land points in the cmorised NEMO output? It was optional for CMIP5 and we didn't do it, is it mandatory for CMIP6?

**Comment by etiennesky** [comment]
Hi can we discuss this on the portal ? https://dev.ec-earth.org/issues/373

**Comment by goord** [comment]
Has been fixed by NEMO output configuration.
