### ISSUE TITLE
error query - jsonloader, unknown method griddes

### ISSUE THREAD

**Issue by jmcgove** [goord/ece2cmor3#40]
Hi, 

Does anyone know these errors I get when I try a test run (./ece2cmor.py). 
-   ERROR:jsonloader:Could not find parameter table entry for hfx in table Omon...skipping variable.
Is this just because there is no hfx parameter in the file. Do each of the day, month types (O, CF, AER...SI...) in varlist.json and CMIP6 tables needs to be included
-  Finishes with
AttributeError: Unknown method 'griddes'!
griddes is in ifs2cmor.py. Does something need to be specified in ifs2cmor.py? Is this due to a grid inconsistency or other? 

(I am using resources/varlist.json, resources/metadata-template.json files, CMIP6 table in cmor/TestTables/ CMIP_xxx.json files,  input file created with fixmonths.py)

Thanks

**Comment by jmrgonza** [comment]
Not sure about the error, but 'griddes' looks like a cdo command. Did you install the cdo python extension, as listed in the requirements.txt file?

**Comment by jmcgove** [comment]
I installed the python-dateutil in requirements, is that the extension? I get same error. Also in requirements it says cdo 1.3.2, but I have cdo 1.7.2, would the version affect it?

**Comment by goord** [comment]
Hi @jmcgove , can you load your python environment, type python and in your python shell type the following:
```
import cdo
app = cdo.Cdo()
app.griddes(input = <path to ICMGG-file>)
```
to see whether your python wrapper allows you to execute the grid description command?

**Comment by goord** [comment]
BTW don't worry about the hfx error. Not all ocean variables are fixed yet, this message does not influence your atmosphere cmorization.

**Comment by jmcgove** [comment]
Ok thanks. Seems the error is to do with cdo not finding griddes. When I type those in I get 
 File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/cdo.py", line 221, in __getattr__
AttributeError: Unknown method 'griddes'!
So I will need to get griddes installed, set it, that's right?

**Comment by goord** [comment]
Yes I think your python wrapper is out of date. I will look at it over the weekend.

**Comment by jmcgove** [comment]
Hmm.. so I need an updated wrapper? Thanks for looking if you can.

**Comment by goord** [comment]
When I look at the cdo.py, it collects all its attributes (functions) from the cdo command: 'cdo --operators', so you need to check the following:
- do you define the environment variable CDO? If so, type ${CDO} --operators and check whether griddes is defined
- if cdo is in your $PATH, just check whether cdo --operators contains griddes.
- Check whether the python wrapper can 'load' the cdo binary, i.e. your cdo version should be > 1.7.0

**Comment by jmcgove** [comment]
Thanks. Two first points are good - ${CDO} --operators gives griddes defined and cdo --operators also contains griddes. but python commands still give same error.

The last - I use cdo version 1.7.2. (>1.7). The python commands above show cdo.py in    
File "build/bdist.linux-x86_64/egg/cdo.py", line 221, in getattr.
I can see where cdo.py is, but can't find it (tried grep, locate). 
There is also cdoapi.py in ece2cmor3. In it only has import cdo, does not specify version number.

Which is the wrapper to check, cdo.py (I would say so) or cdoapi.py?
Thanks

**Comment by goord** [comment]
cdo.py is the wrapper provided by the MPI people. In this file you will find a piece of code called getOperators() which calls "cdo --operators" to define the attributes. But it only does this if the version is correct, in my case > 1.7.0. This is all very strange...

**Comment by jmcgove** [comment]
Do you have a copy of cdo.py, or is it within the package / available somewhere to see?

**Comment by goord** [comment]
Are you running anaconda or have manually installed the dependencies? In the latter case you can just 'pip install cdo' within your python environment.

**Comment by jmcgove** [comment]
Manually. 
pip install cdo gives:
Requirement already satisfied (use --upgrade to upgrade): cdo in /usr/lib/python2.7/site-packages/cdo-1.2.6-py2.7.egg
and pip install cdo --upgrade: 
Installing collected packages: cdo
  Found existing installation: cdo 1.2.6
    Uninstalling cdo-1.2.6:
Looks only cdo 1.2.6 can be seen, even though v1.7.2 is installed. I guess this is why there is the griddes error. I need to see if I can get it up to 1.7.2?

**Comment by jmrgonza** [comment]
There are different version numbers for the cdo program and the python bindings (wrapper). In your installation, it seems that you are using a version of the wrapper (1.2.6) that is lower than that in the requirements (1.3.2).  I think that the latest version of the python bindings is 1.3.3.
I would recommend you to upgrade the python wrapper, since the one that you are using seems to come from a binary distribution and is possible that it packs a different version of the cdo program.

**Comment by jmcgove** [comment]
When I upgrade I think binding version 1.3.3 is partially downloaded, or at least is seen; what I get first with pip install cdo --upgrade:
Collecting cdo
  Downloading cdo-1.3.3.tar.gz
Requirement already up-to-date: six in /usr/lib/python2.7/site-packages (from cdo)
Installing collected packages: cdo
  Found existing installation: cdo 1.2.6
    Uninstalling cdo-1.2.6:
But then an exception/ permission denied error
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/cdo-1.2.6-py2.7.egg
Prob to do with administrative rights, will see with IT.

**Comment by jmcgove** [comment]
I need to wait for root admin next week. I will also start looking at putting ece2mor3 on cca. 
For cca is a certain cdo / python version needed for ece2mor3 to work? (Is pip install cdo needed, say?). (I loaded default python and cdo(1.6.1) and doing import cdo in python on cca to see, get (also tried with cdo 1.7.2, get same):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cdo

Regarding cmor for ece2mor3, I saw in a thread 5 mth ago, https://dev.ec-earth.org/issues/255):
cmor on cca 'this module does not provide (for the time being) the corresponding python package, it only provides the library libcmor.a.
We will ask them to install it'
Is cmor on cca now ok to be used for ece2cmor3 (vrs now 3.1.2)?
Thanks

**Comment by pabretonniere** [comment]
Hi @jmcgove 

Just today I was talking with @goord about this. I sent an email to the ecmwf support asking for a module containing the python library of cmor3.2.2 so we can use it in ece2cmor. I'll post here their answer

**Comment by jmcgove** [comment]
Hi @pabretonniere, thanks! Regarding versions, do you know what cdo/python/python wrapper version is needed / you used to run ece2mor3 on cca? Are these already/ do these need to be updated on cca?

**Comment by goord** [comment]
You will need to create a virtual environment, via pip install a recent version of cdo.py and before you start load the default cdo module. I have copied my python virtual environment onto ecfs (ec:/nkgo/primavera/pycmorenv.tar.gz), you may want to try it (untar and source pycmorenv/bin/activate), but you will need to install the native libraries (CMOR) for it to work correctly I think.

**Comment by jmcgove** [comment]
I will wait for the latest cmor on cca. I got cdo wrapper updated and running ece2mor3.py on the other server, specifying input files, start date, and options (.json files, freq, tmp directoy, cmor tables ...) ok.

It runs through much further than before, but not completely. There are cdo warnings about no variable 134, that's ok. The run ends saying there is no ps_Amon.nc file, seems to be with cdo griddes.
Error in calling operator griddes with:
>>> cdo -O griddes /data/jmcgovern/p-process-ECEarth/ece2cmor3-master2/ps_Amon.nc<<<
STDOUT:
STDERR:cdo griddes: Open failed on >/data/jmcgovern/p-process-ECEarth/ece2cmor3-master2/ps_Amon.nc<
No such file or directory

Looks like ps_Amon.nc has not been created (with cdo-griddes). Except cdo --operators shows griddes ok and i updated the wrapper to 1.3.1 from before.  Prob something else ...

**Comment by goord** [comment]
Hi @jmcgove, this error occurs because CMOR wants the grid description, and takes the first task result to get it, which is the surface pressure in Amon. Can you post the complete output, so we can figure out why monthly surface pressures were not created?

**Comment by jmcgove** [comment]
So you saw this issue before.. Ok, I called 
./ece2cmor.py --tabdir /data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/TestTables/  /data/jmcgovern/p-process-ECEarth/ece2cmor3-master2/scripts/ 1990-01-01
and the complete output I got was
[test.txt](https://github.com/goord/ece2cmor3/files/1138264/test.txt)

**Comment by goord** [comment]
Ok I see the bug here, I will fix it today

**Comment by goord** [comment]
@jmcgove Apparently this issue was fixed in the primavera branch but never merged to the master branch. After git pull you should be able to get past the surface pressure monthly means. BTW are you processing primavera output? Because in that case we have a dedicated primavera branch...

**Comment by jmcgove** [comment]
Thanks. The error is gone. I'm not processing primevera, just using the trunk and test files for moment. 
I now have what seems a syntax error 
TypeError: unsupported operand type(s) for *: 'int' and 'instance' in cmor_utils.py. 
I came across unsupported operand before, but not 'instance'. I checked, came across:
you need to perform your operations on the numeric value, (int or float), of the text in the control instances, rather than the controls themselves'
Trying to see this, I guess it is to do with the syntax in the file.

**Comment by goord** [comment]
Hi @jmcgove can you git pull, run again and post the output please?

**Comment by jmcgove** [comment]
Hi @goord, I ran the latest (I see log.info were added to cmor_util), get the same error. It looks like it could be to with offset*interval, line 77, and also at line 79 + 81. Output is here 
[test.txt](https://github.com/goord/ece2cmor3/files/1142453/test.txt)

**Comment by goord** [comment]
Ok, apparently there is something different in your dateutil installation. Can you run python (the same version + environment you use for running ece2cmor3) and type the following in the interpreter:
```
import dateutil.relativedelta
interval = dateutil.relativedelta.relativedelta(days = 5)
print interval
print 2*interval
```
If you're using python 3, change the print statements into print(...)

**Comment by jmcgove** [comment]
Running pyth in ece2mor3 dir. gives error TypeError: unsupported operand type(s) for *: 'int' and 'instance' for the 2nd print statement. When run in dateuil dir. get no error. 

Perhaps to do with specifying the path. In requirements.txt there is python-dateuil-2.6 which I have. When I do pip install requirements.txt, I get
pip install requirements.txt 
Collecting requirements.txt
Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by jmrgonza** [comment]
You missed an option: the command is `pip install -r requirements.txt`.

For the record, I get errors related to frequency values in the tests when I use cmor 3.2.4 from the pcmdi anaconda repository. The same tests work with cmor 3.2.3.

**Comment by jmcgove** [comment]
Thanks. pip install -r requirements.txt dowloads all the packages ok. After doing pip install -r requirements.txt, get the same instance error when I run python with the above (dateuil) and also ece2mor3.py. Will try again..
pip install -r requirements.txt dowloads all the packages ok, but finishes trying to uninstall cdo1.3.3 (does'nt, needs permission). Is cdo-1.3.3 not needed (I updated it earlier on for this)? 
(Found existing installation: cdo 1.3.3
    Uninstalling cdo-1.3.3:
Exception:
Traceback (most recent call last):  
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/cdo-1.3.3-py2.7.egg-info/PKG-INFO' )

**Comment by jmcgove** [comment]
Hi @pabretonniere, was wondering if you heard back from ecmwf about a module with a cmor3.2.2 python library for ece2cmor on cca.

**Comment by pabretonniere** [comment]
Hi @jmcgove ,

Yes, sorry I didn't come back to you. Actually it is CMOR 3.2.3 (version from the ece2cmor requirements) but they did install it as a module.

You can do:
```
prgenvswitchto gnu 2>/dev/null
module load python cmor/3.2.3 
```

**Comment by jmcgove** [comment]
Thanks! loads fine. When I run requirements in ece2mor3 after (pip install -r requirements.txt) get disk quota exceeded (Disk quota exceeded: '/home/ms/ie/dujm/.pip') even though ~half of the space (~1T) is available on /home (df -h). Does pip take up this much space? (ece2mor3 is set up on scratch cca). Or prob has to do with something else.

**Comment by goord** [comment]
Changed cdo from 1.3.2 to 1.3.3, pip works now, at least on my system
