### ISSUE TITLE
master and primavera branch

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#41]
I can process NEMO output with the master branch, but when trying to process IFS output I get

```
Traceback (most recent call last):
  File "./ece2cmor.py", line 68, in <module>
    main(sys.argv[1:])
  File "./ece2cmor.py", line 63, in main
    maxsizegb = args.tmpsize)
  File "/home/sm_wyser/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 131, in perform_ifs_tasks
    outputfreq = outputfreq,tempdir = tempdir,maxsizegb = maxsizegb)):
  File "/home/sm_wyser/ece2cmor3/ece2cmor3/ifs2cmor.py", line 88, in initialize
    ifs_grid_descr_ = cdoapi.cdo_command().get_griddes(ifs_gridpoint_file_) if os.path.exists(ifs_gridpoint_file_) else {}
  File "/home/sm_wyser/ece2cmor3/ece2cmor3/cdoapi.py", line 59, in __init__
    self.app = cdo.Cdo()
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 87, in __init__
    self.operators              = self.getOperators()
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 261, in getOperators
    if (parse_version(getCdoVersion(self.CDO)) > parse_version('1.7.0')):
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 40, in getCdoVersion
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group' 
```

Interestingly enough, the IFS output processing worked fine with the PRIMAVERA branch but not the NEMO output processing (see #31)

**Comment by goord** [comment]
Ah I see the error in the primavera branch of the master script now, it does the ocean twice!

**Comment by goord** [comment]
Fixed the double ocean cmorization problem finally, rev. 16e1b12df990088c200c1369f369c42cf6f14acc

**Comment by goord** [comment]
Klaus, can you load your conda enviroment and type the following:
```
python
>>> import cdo
>>> app = cdo.Cdo()
```
Does it give the same error?

**Comment by klauswyser** [comment]
Here is what I get:

```
>>> import cdo
>>> app=cdo.Cdo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 87, in __init__
    self.operators              = self.getOperators()
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 261, in getOperators
    if (parse_version(getCdoVersion(self.CDO)) > parse_version('1.7.0')):
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/cdo.py", line 40, in getCdoVersion
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

I have updated cdo to version 1.8.2, get the same error. Is it a problem with my anaconda env?

**Comment by goord** [comment]
I have come across this issue myself, but I can't remember the solution. Could it be that some cluster module or appended path exposes an older version of cdo?

**Comment by klauswyser** [comment]
It's pretty weird. I have load module cdo in my bash_profile, but somehow cdo gets broken when I activate the Anaconda env and therefore `cdo.Cdo()` results in an error. The fix is
```
source activate CMOR
module unload cdo
module load cdo
python
>>> import cdo
>>> cdo.Cdo()
```
(CMOR is the name of my Anaconda env)

For the time being it's OK to have this workaround, but it's not nice in the long run. I'll ask the guys from the computer center if this is a bug of Anaconda and if so if it can be fixed.

With the workaround I can now process atm and oce output without problem, therefore closing the issue.

**Comment by klauswyser** [comment]
Update: I consulted the computer center, and they discovered that cdo in source forge dosn't come with the correct dependencies: cdo needs libicui18n.so.58 (whatever that is) but apparently "our" anaconda comes with icui-54. In principle icui could be updated from conda-forge, but unfortunately icui has quite many dependants (scipy and numpy among others), and I am not sure what happens with the CMOR3 library if these packages are changing.

**Comment by goord** [comment]
That is what I suspected too. I am not sure whom to report this to, because I don't know whether the CDO developer team at MPI is releasing that conda package
