### ISSUE TITLE
missing ocean variables with primavera output

### ISSUE THREAD

**Issue by etiennesky** [goord/ece2cmor3#42]
when running the tool on recent primavera output the following problems appear

1) grid_u/v/w variables u2o, umo, uto, uso, v2o, vmo, vto, vso, w2o, diffvho and wmo are missing 
2) most fluxes (in _SBC file) are missing, except for wfo : rsntds, qsr3d, rsdo, precip, friver, ficeberg2d 
3) rhopoto (potential density) is missing because it is not requested but we think it is necessary. Is there a way to add it manually?
4) For 1d sea-ice the following variables are missing : siu, siv, sithick, sistrxdtop, sistrydtop
5) For 1mo sea-ice only sipr is there... maybe it is not looking in the _icemod.nc file ?

**Comment by klauswyser** [comment]
Are these variables missing in the NEMO output, or are they just not handled properly by the ece2cmor3 tool?

**Comment by etiennesky** [comment]
Yes they are in the input files, however the fluxes are in the _SBC.nc file and the ice variables in the _icemod.nc files. In parallel I asked Pierre-Antoine to check but I would like to know if the problem is also found by others.

**Comment by goord** [comment]
Are the variables in your varlist.json, i.e. do you request ece2cmor3 to process the variables? If so, it should complain somewhere that it cannot find them, either not in the dictionary nemopar.json or in your nemo output...

**Comment by etiennesky** [comment]
I think it is because they are missing from varlist.json here is what I have

    "SImon": [
        "sipr"
    ],

     "SIday": [
        "sithick",
        "siu",
        "siv",
        "siconc"
    ],

Sorry I haven't been very involved in the cmorization so far.

We have to add  the variables manually, they are not populated by the data request in any way?

**Comment by goord** [comment]
The varlist.json is a bit of a complicated story... in the main branch, the resources/varlist.json is the CMIP6 data request, or at least what we believe we can deliver from it. In the primavera branch there is also the file resources/data_request/PRIMAVERA/varlist.json which contains the PRIMAVERA-specific variables (these have to be processed separately because they also use different tables etc.). In any case, in these files you find the Omon and Oday variables.

**Comment by etiennesky** [comment]
sorry I only checked the sea-ice variables -- siu,siv and sithickare in the varlist.json but are not output.

other variables like friver, ficeberg2d,  rsntds, rsdo,hfds are in the CMIP6 varlist.json but not output, so in this case we should check the error logs.

Sorry Gijs but I still don't understand how the varlist.json files are generated, these are from the data requests directly or edited by hand?

**Comment by goord** [comment]
The varlist.json in resources has been generated by me from the data request. It is the default variable list, so when you run ece2cmor.py without --vars <FILE> option. You can however run a subset yourself by e.g. copying the included varlist.json and removing a bunch of variables and specifying the new file as a command-line option.

**Comment by goord** [comment]
So you should think of the resources/varlist.json containing the 'maximal set' of variables we can produce. Hence, if the ec-earth output is configured correctly, ece2cmor.py should run without errors if you choose this variable list.

**Comment by pabretonniere** [comment]
Hi. Jumping in. Yes, it's an issue of our varlist and nemopar not corresponding to our nemo files. But I could now produce almost all the variables that @etiennesky  was reporting missing.  Etienne, I will show you tomorrow and we can discuss about the few variables that are left but this is a local issue I think. Thanks Klaus and Gijs for your answers anyway.

**Comment by klauswyser** [comment]
An important question: what set of xios files do I get when I check out the projects/primavera branch from the dev portal? Can the output produced by these files be processed by ece2cmor3 without problems /no action needed? I haven't tested myself, but maybe somebody else has tried it already.

**Comment by goord** [comment]
Hi Klaus,
You should be able to produce most of them. There are still a couple of
variables that we agreed to produce but are currently not able to do so.

Op 30 jun. 2017 8:21 a.m. schreef "klauswyser" <notifications@github.com>:

**Comment by klauswyser** [comment]
I am afraid that "should work" isn't good enough. Has anybody really tried checking out the primavera branch, make a run with the provided ppt and xios files, and then process the output with ece2cmor3? Does this really work?

@goord mentioned that there are still some variables missing in the output, we probably cannot do much about it at this moment. But, do these missing variables harm the processing by ece2cmor3? Does a missing variable just trigger a warning and the processing continues, or does a missing variable grind the thing to halt?

**Comment by etiennesky** [comment]
@klauswyser me and @pabretonniere are testing ece2cmor3 with output produced by the primavera branch, so things work but some variables are not produced by ece2cmor3. In fact this whole issue is with the primavera output, not standard cmip6.

**Comment by etiennesky** [comment]
Just a follow up, @pabretonniere has fixed most of the missing variables we will update the github as soon as possible.

**Comment by goord** [comment]
Yeah I was just a bit optimistic when I filled in the data request for the ocean variables, it's better to promise too much than too little in this case.

**Comment by pabretonniere** [comment]
Hi. 

I just made created a new branch (develop-primavera) with the changes that allowed me to run both CMIP6 and PRIMAVERA CMORizations, just changing the parameter --tabid. 
You'll notice that there are quite a lot changes, that's why I created a new branch and not made commits in the primavera branch directly.
Let me know if you can produce more variables.
I'm running with the files that @etiennesky produced at BSC. Etienne, correct me if I'm wrong but they have been produced with the latest PRIMAVERA changes from ecearth.

**Comment by goord** [comment]
Let's report any problems with missing variables for CMIP6 as separate issues.
