### ISSUE TITLE
missing variables in NEMO output

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#44]
Following up on #3:

Processing the output from a run with the PRIMAVERA configuration results in dozens of missing variables errors:
```
...
ERROR:nemo2cmor:The source variable qt could not be found in the input NEMO data
ERROR:nemo2cmor:The source variable scsaltot could not be found in the input NEMO data
ERROR:nemo2cmor:The source variable sctemtot could not be found in the input NEMO data
...
```
I have used the default varlist and metadata file that comes with ece2cmor.

**Comment by goord** [comment]
Hi Klaus,

did you run with the --oce flag? Because if not, it will issue an error for every atmosphere variable...
Does the list of missing variables resemble the one reported in #3?

**Comment by klauswyser** [comment]
@goord: yes to both questions.

**Comment by etiennesky** [comment]
I would suggest you move over to issue #42 if this is with primavera output & tables.

**Comment by klauswyser** [comment]
Sorry, didn't think of #42, let's continue the discussion there.
