### ISSUE TITLE
atmosphere processing for primavera fails

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#45]
I have made a run with the Primavera version and Primavera output, then split the atmosphere output in 3-hourly and 6-hourly files with filter6hr.py. After that I tried to run ece2cmor.py with the `-a` flag:

``./ece2cmor.py --exp pr03 -a --freq 3 tmp-pr03/3hr 199001``

I get errors about missing sea-ice and ocean variables:
```
ERROR:jsonloader:Could not find parameter table entry for masscello in table Omon...skipping variable.
ERROR:jsonloader:Could not find parameter table entry for hfbasin in table Omon...skipping variable.
ERROR:jsonloader:Could not find parameter table entry for hfx in table Omon...skipping variable.
...
```
Some atmosphere variables  are also missing:
```
ERROR:jsonloader:Could not find cmor target for variable snw in table day
ERROR:jsonloader:Could not find cmor target for variable mrro in table day
ERROR:jsonloader:Could not find cmor target for variable orog in table AERmon
ERROR:jsonloader:Could not find cmor target for variable ps in table AERmon
```
And then it crashes with
```
Traceback (most recent call last):
  File "./ece2cmor.py", line 89, in <module>
    main(sys.argv[1:])
  File "./ece2cmor.py", line 72, in main
    startdate = dateutil.parser.parse(args.date)
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/sm_wyser/.conda/envs/CMOR/lib/python2.7/site-packages/dateutil/parser.py", line 581, in parse
    ret = default.replace(**repl)
ValueError: month must be in 1..12
```

**Comment by klauswyser** [comment]
Stupid me, the date should be given as `YYYY-MM-DD`, not `YYYYMM`, so the last error is obsolete. But the attempted processing of ocean variables despite the `-a` flag, and the missing atmosphere variables are still open issues that we should look at.

**Comment by pabretonniere** [comment]
Hi @klauswyser 

I was trying to reproduce your issue and even if YYYY-MM-DD indeed solves the issue, YYYYMMDD should also work. It just needs the day. For the missing atmospheric variables, as mentioned in #44, I created a new branch that produces almost all atmospheric and ocean primavera variables.

**Comment by goord** [comment]
Klaus, for the present AMIP run I dismissed those variables. snw and mrro cannot be produced with the snow/soil parametrization in IFS I think, and I dismissed the AERmon variables because those are the only 2 variables in that table that we can produce, but people might as well get air pressure and orography from other monthly tables.

BTW Our first year of AMIP data has been validated at the esgf node: no issues were reported, but he validation is terribly slow...

**Comment by klauswyser** [comment]
@goord: mrro is runoff which is in the IFS output (RO), and snw is the snow water equivalent which is saved by IFS as SD. I think we could easily deliver these variables.

Great to hear the our cmorized files passed the 1st test, good work from you, Gijs!

**Comment by klauswyser** [comment]
@pabretonniere
> I created a new branch that produces almost all atmospheric and ocean primavera variables.

Great. Will these changes eventually be merged to the primavera branch to have it all in one place?

**Comment by pabretonniere** [comment]
@klauswyser : yes. I created a separate branch for the moment because we are still integrating some variables and haven't fully validated everything yet but as soon as we have everything, I'll do the merge request. You can of course test the branch if needed.
