### ISSUE TITLE
ece2cmor fails when not finding a variable

### ISSUE THREAD

**Issue by pabretonniere** [goord/ece2cmor3#50]
Hi,

ece2cmor is failing (and exiting) when it can't find a variable that was asked in the varlist.
the ifspostproc just shows a warning but then, the cmorization itself fails when trying to open the nc file instead of just going to the next variable. This is an issue of ny varlist that didn't comply with my IFS outputs but it makes the whole process fail. 

Error in calling operator setgridtype with:
>>> /usr/local/apps/cdo/1.7.2/bin/cdo -O -f nc -P 4 setgridtype,regular -daymean -selmon,2 -selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 /scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/atm-CMIP6-3h-195002/mrrob_Eday.nc<<<
STDOUT:

STDERR:cdo setgridtype: Started child process "daymean -selmon,2 -selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe1.1)".
cdo(2) daymean: Started child process "selmon,2 -selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe2.1)".
cdo(3) selmonth: Started child process "selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe3.1)".
cdo(4) selcode (Warning): Code number 9 not found!
cdo(4) selcode (Abort): No variables selected!

ERROR:cdoapi:(returncode:1) cdo setgridtype: Started child process "daymean -selmon,2 -selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe1.1)".
cdo(2) daymean: Started child process "selmon,2 -selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe2.1)".
cdo(3) selmonth: Started child process "selcode,9 /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 (pipe3.1)".
cdo(4) selcode (Warning): Code number 9 not found!
cdo(4) selcode (Abort): No variables selected!

INFO:postproc:Post-processing target tasmin in table Amon from file /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 with cdo command -monmean -daymin -setgridtype,regular -selmon,2 -selcode,202
INFO:postproc:Post-processing target tasmax in table Amon from file /scratch/ms/spesiccf/c3b/a0oe/19500101/fc0/runtime/Output_1/out-195002/3hr/ICMGGa0oe+195002 with cdo command -monmean -daymax -setgridtype,regular -selmon,2 -selcode,201
 (...)
INFO:ifs2cmor:Creating time axis using variable mrrob...
Error in calling operator showtimestamp with:
>>> /usr/local/apps/cdo/1.7.2/bin/cdo -O showtimestamp /scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/atm-CMIP6-3h-195002/mrrob_Eday.nc<<<
STDOUT:

STDERR:cdo showtimestamp: Open failed on >/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/atm-CMIP6-3h-195002/mrrob_Eday.nc<
No such file or directory

Traceback (most recent call last):
  File "./ece2cmor.py", line 90, in <module>
    main(sys.argv[1:])
  File "./ece2cmor.py", line 85, in main
    maxsizegb = args.tmpsize)
  File "/lus/snx11062/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 137, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks,cleanup = cleanup)
  File "/lus/snx11062/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 141, in execute
    cmorize([t for t in processedtasks if getattr(t,"path",None) != None])
  File "/lus/snx11062/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 345, in cmorize
    create_time_axes(tskgroup)
  File "/lus/snx11062/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 458, in create_time_axes
    tid = create_time_axis(freq = task.target.frequency,path = getattr(task,"path"),name = tdim,hasbnds = (timop != ["point"]))
  File "/lus/snx11062/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 602, in create_time_axis
    times = command.showtimestamp(input = path)[0].split()
  File "/home/ms/spesiccf/c3b/.local/lib/python2.7/site-packages/cdo.py", line 206, in get
    raise CDOException(**retvals)
cdo.CDOException: (returncode:1) cdo showtimestamp: Open failed on >/scratch/ms/spesiccf/c3b/a0oe/auto-ecearth3/ece2cmor/ece2cmor3/atm-CMIP6-3h-195002/mrrob_Eday.nc<
No such file or directory

**Comment by jmcgove** [comment]
Hi @pabretonniere, I was wondering if you got the run to ignore a missing variable (in your case param 9) and carry on, and not abort (I have a similar error).

**Comment by goord** [comment]
OK, I will try to fix this. I can add a flag to the task when it fails the postproc step and ignore it for the rest of the program.

**Comment by jmcgove** [comment]
Hi @goord , I noticed you made a recent change (839, 12 sept). Perhaps not, I was just wondering if this change was to do with the flagging the task when it fails. Thanks (When I tried this latest, I get aborts when a parameter cannot be found, as before)

**Comment by goord** [comment]
Hi @jmcgove, I am working on that one, expect a push either today or this weekend.

**Comment by jmcgove** [comment]
Hi @goord , the latest update doesn't abort, thanks. There is now output in tmp, for the parameters in the ICM files I used (ua, va, ta, hus, zg). 
I guess the 27_6hrPlevPt.nc files are the 6 hour files? The day (daily) and Amon (monthly average) files have 30 segments and 1 segment (the ICM file is just one month, starting 1990-01-01, so that makes sense). These are the cmorised files?
