### ISSUE TITLE
ERROR: cmor target for variable x in table y cannot be found

### ISSUE THREAD

**Issue by goord** [goord/ece2cmor3#7]
Upon startup, many log errors are produced indicating that certain variables cannot be found in certain tables. This can occur when a variable in a new version of the tables is renamed or removed. In the first case, we should rename the corresponding variable in varlist.json, in the second case we should remove it.

**Comment by klauswyser** [comment]
I get this error: `ERROR:jsonloader:Could not find cmor target for variable tas in table Amon`

But where is table Amon? Resources/cmip6-cmor-tables is empty, and esources/tables Points to a non-existing directory. I found quite many tables that are distributed with the cmor-3.2.2 library, e.g. `cmor-CMOR-3.2.2/TestTables/CMIP6_Amon.json`, do I need to copy these tables somewhere?

**Comment by goord** [comment]
You need to download the cmip6 tables by typing
```
$ git submodule update --init --recursive
```
within your repository clone. I will add this to the README

**Comment by goord** [comment]
Fixed in b3fd1d7f539727b65fd4096e8fcbdcb08e1734a9
