### ISSUE TITLE
Dependence on esmf broken in master

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#79]
Trying:
 conda env create -f environment.yml
in the master branch:

ResolvePackageNotFound: 
  - esmf ESMF_6_3_0rp1_ESMP_01 np111py27_2

Tried to change to:
  - esmf ESMF_6_3_0rp1_ESMP
But then getting the hdf5 1.8.* troubles.

See also issue #72 and #74

**Comment by goord** [comment]
Also cdo seems to be broken since a week or two. I managed to create an env file with cmor-3.2.8 and cdo-1.8.2 which seems to work, I just have to fix some tests before I push it.

**Comment by goord** [comment]
Can you check again with the newest master branch?

**Comment by treerink** [comment]
I have still troubles, I get now the following:

Trying:
conda env create -f environment.yml
in the master branch:

ResolvePackageNotFound: 
  - intel-openmp 2018.0.0 hc7b2577_8

**Comment by goord** [comment]
Can you check once more with the newest master branch?

**Comment by treerink** [comment]
Ok for linux works fine now, so close this issue.
However for Mac still unresolved packages.
