### ISSUE TITLE
Unresolved packages on mac while creating the ece2cmor3 conda environment

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#80]
On Mac OS unresolved packages for:
conda env create -f environment.yml

**Comment by treerink** [comment]
Several packages need their mac equivalent dependency. By using e.g.
 conda info wheel
And figuring out which one matches the one which is used on linux, often the mac equivalent dependency can be found:

- wheel=0.30.0=py27h2bc6bb2_1 
replace on mac by:
- wheel=0.30.0=py27h677a027_1

- intel-openmp=2018.0.0=hc7b2577_8
replace on mac by:
- intel-openmp=2018.0.0=h8158457_8

- libgcc=7.2.0=h69d50b8_2
replace on mac by:
- libgcc=4.8.5=hdbeacc1_10

- libgfortran=3.0.0=1
replace on mac by:
- libgfortran=3.0.1=h93005f0_2

- mkl=2018.0.1=h19d6760_4
replace on mac by:
- mkl=2018.0.1=hfbd8650_4

- numpy=1.13.3=py27hbcc08e0_0
replace on mac by:
- numpy=1.13.3=py27h62f9060_0

No mac equivalent found for:
- libgcc-ng=7.2.0=h7cc24e2_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- util-linux=2.21=0
- cmor=3.3.0=py27he7c6f3b_0                the absence of this one blocks this issue

However, the fact that there seems to be no any conda cmor package for mac, makes it impossible yet to solve this issue.

**Comment by goord** [comment]
rev. a73fb8688d30a8464101f1c14a4d1275cef0f58e. The max-osx environment still depends on cmor-3.2.7, will update whenever they make newer versions available .
