### ISSUE TITLE
Problem processing var119 and var120 for Primavera

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#81]
When trying to process var119 or var120 for Primavera I get:

```
ERROR:cdoapi:(returncode:1) cdo monmean: Started child process "expr,var119=100*(var141>0) -setgridtype,regular -selmon,1 -selcode,141 /scratch/local/3hr/ICMGGps11+198001 (pipe1.1)".
cdo(2) expr: Started child process "setgridtype,regular -selmon,1 -selcode,141 /scratch/local/3hr/ICMGGps11+198001 (pipe2.1)".
cdo(3) setgridtype: Started child process "selmon,1 -selcode,141 /scratch/local/3hr/ICMGGps11+198001 (pipe3.1)".
cdo(4) selmon: Started child process "selcode,141 /scratch/local/3hr/ICMGGps11+198001 (pipe4.1)".
cdo(2) expr (Abort): expr_var_con: operator > unsupported!
```
 
```
ERROR:cdoapi:(returncode:1)` cdo monmean: Started child process "expr,var120=(var141>0)*(var146+var147) -setgridtype,regular -selmon,1 -selcode,146,147,141 /scratch/local/3hr/ICMGGps11+198001 (pipe1.1)".
cdo(2) expr: Started child process "setgridtype,regular -selmon,1 -selcode,146,147,141 /scratch/local/3hr/ICMGGps11+198001 (pipe2.1)".
cdo(3) setgridtype: Started child process "selmon,1 -selcode,146,147,141 /scratch/local/3hr/ICMGGps11+198001 (pipe3.1)".
cdo(4) selmon: Started child process "selcode,146,147,141 /scratch/local/3hr/ICMGGps11+198001 (pipe4.1)".
cdo(2) expr (Abort): expr_var_con: operator > unsupported!
```

BTW: what are var119 and var120? I cannot find these codes in ifs.par, maybe that's the reason for the problem?

**Comment by goord** [comment]
Hi klaus, you should search in ifspar.json, I'm guessing snow cover, but
I'm not sure! Apparently your CDO version doesn't support comparison
operators in expressions...

Op 12 dec. 2017 2:50 p.m. schreef "klauswyser" <notifications@github.com>:

**Comment by klauswyser** [comment]
Indeed, cdo 1.6.2  doesn't have the comparison feature in expr, and therefore fails. With cdo 1.7.0 things work fine. Maybe good to have a note about the minimum requirement for cdo in the doc? @treerink ?

And yes, @goord is right, ifspar.js is the place to look for variables. I went through the list and have a couple of questions and comments, but will do so in a new issue.

**Comment by treerink** [comment]
Hi Gijs,

About cdo recommendations / dependencies:

In environment.yml:
cdo=1.8.2=0
python-cdo=1.3.3=py27_0 
Shouldn't we just try cdo 1.8 here?

In requirements:
cdo==1.3.3                                    
No issue here I think to change to 1.8 here?

**Comment by goord** [comment]
Hi Thomas, confusingly enough the cdo binary and its python wrapper (python-cdo) have different version numbers, so I'm not sure whether python-cdo 1.8 already exists?

**Comment by klauswyser** [comment]
I actually use cdo-1.7.0 with ece2cmor3, works fine. Not sure though which python-cdo wrapper I am using.

**Comment by treerink** [comment]
The cdo version 1.7.0 or higher is recommended because of comparison operators in expressions. Latest cdo version is 1.9.2, but not tested with ece2cmor3. 

The cdo version 1.7.0 recommendation is added to the README and to the requirements.txt

Indeed the python-cdo=1.3.3=py27_0 is the version of the python cdo wrapper, which has its own version numbering.

Closing the issue
