### ISSUE TITLE
setgridtype,regular before or after expr in derived variables from IFS

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#84]
IFS data need to be remapped (interpolated) to the regular Gauss grid, and the question is if this should happen before or after computations/manipulations are done to get derived variables. Currently this is done after the remapping, here for example for the snow depth:

```-expr,'var115=1000*var141/var33' -setgridtype,regular```

This will give a slightly different result if the data manipulation would be done before the interpolation, e.g.

``` -setgridtype,regular -expr,'var115=1000*var141/var33'```

Which one is correct? I personaly would tend to favour the 2nd line, but I acknowledge that a strong reason for the 1st line is that it produces consistent results. Consistent in the sense that if somebody takes the snow depth from the model (var141) interpolated to the regular grid and divides with the snow density interpolated to the regular grid, he or she will get the same snow depth as is saved in the CMIP6 archive which wouldn't be the case if the data would have been processed with the 2nd line.

Any opinions?

**Comment by goord** [comment]
I implemented the first choice for the spectral transform by the way, so it is only a small effort to change this. The second option is faster for processing, but if both methods produce similar interpolation errors, I think the first option is preferable for consistency no?

**Comment by klauswyser** [comment]
> ...if both methods produce similar interpolation errors...

That's not the case, the results will be different in the two cases.  Take snow cover (snc) for example:
```
var119=100*(var141>0)
```
If you evaluate the expression first and interpolate after the result will be somwhere between  0 and 100 in each gridpoint, but if you do the spatial interpolation before evaluating the expression then the resulting field will be either 0 or 100 in each gridpoint. To me the 1st option sounds more realistic, but I don't know for sure.

**Comment by klauswyser** [comment]
There is also a consistency issue with the way how spectral and gridpoint variables are treated. Spectral variables are first interpolated to the the regular Gauss grid before evaluating any expression, there is no other way to do it. Therefore it may make sense to do the same for gridpoint variables, or?

This is important if we have derived variables that are a combination of spectral and gridpoint variables, in that case even gridpoint varialbes must be interpolated first. (Do we have any derived variables that are a combination of gridpoint and spectral variables? Humidity flux (qv and qu) in the atmosphere maybe?) 

Consistent post-processing of spectral and gridpoint variables is in my opinion the most important argument here. The current way of doing the remapping before evaluating any expression is doing exactly this, therefore I suggest to leave everything as is and close the issue.

Feel free to reopen if you disagree.

**Comment by goord** [comment]
FYI, we don't have humidity fluxes available, we don't support combinations of spectral and gridpoint variables (yet...).
