### ISSUE TITLE
processing with ece2cmor.py stalls

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#86]
Processing 3-hourly output all of a sudden hangs, no idea why. 

I use a node with 16 cores with npp=16 and ncdo=1 (my cdo doesn't support OpenMP). I don't think it's a memory issue because memory is 256 GB on the node. I have also tested with npp=1 and ncdo=1, doesn't help.

Counting occurrences of 'INFO:postproc' in the logfile reveals that with npp=16 and ncdo=1 I have processed 137 variables before it halts, while with npp=1 and ncdo=1 the processing stops after 37 variables already.

Any idea what could cause this problem?

**Comment by klauswyser** [comment]
Something else that could be important: despite the logfile telling that 137 variables have been processed, not a single variable has been saved in the cmor/CMIP6... directory, no idea where they went.

**Comment by klauswyser** [comment]
From the logfile:
```
INFO:ece2cmorlib:Selected 136 IFS tasks from 136 input tasks
INFO:ifs2cmor:Inspecting 136 tasks.
INFO:ifs2cmor:Validated 136 tasks for processing.
INFO:ifs2cmor:Executing 136 IFS tasks...
INFO:ifs2cmor:Post-processing 1 IFS tasks...
INFO:postproc:Post-processing target land in table fx from file /scratch/local/3
hr/ICMGGps11+198101 with cdo command -setgridtype,regular -selcode,172 -seltimes
tep,1
INFO:ifs2cmor:Post-processed batch of 1 tasks.
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
INFO:ifs2cmor:Post-processing 136 IFS tasks...
```
So yes, there seems to be 137 tasks in total, consistent with the 137 postproc occurrences. The question is then why I don't get any output from all this post-processing.

**Comment by goord** [comment]
Hi Klaus, all the intermediate netcdf files should be in your temp directory. After post-processing, the cmorization should read those and write the correct nc files in your cmor directory. Does cmor complain about your metadata in the log file (because that is a common problem)?

**Comment by goord** [comment]
BTW note that sometimes the post-processing tasks are highly imbalanced, you could ssh to your node and see whether a cdo process is still running...

**Comment by klauswyser** [comment]
After the processing stops, there are still 2 cdo processes, but they appear to be just hanging (sleeping) and remain like this "forever":
 ```
 6154 sm_wyser  20   0 4842m 472m  15m S  0.0  0.2   0:04.91 python             
 7006 sm_wyser  20   0  459m 141m 5296 S  0.0  0.1   0:00.74 cdo                
 7118 sm_wyser  20   0  459m 141m 5296 S  0.0  0.1   0:00.74 cdo                
```
I find 129 nc files in tmpdir (why not 137?), nothing happens any longer. And no files have been saved in the cmor directory.

**Comment by klauswyser** [comment]
I  started playing with varlist.json, adding and removing variables. It turns out that if I remove ua850 and va850 everything works fine.

I then had a look at the ICMSH file that was created by filter6hr.py, and it seems that this file is corrupt:
```
   File format : GRIB
    -1 : Institut Source   Ttype    Levels Num    Points Num Dtype : Parameter ID
     1 : ECMWF    unknown  instant       1   1     65792   1  P16  : 131.128       
     2 : ECMWF    unknown  instant       1   1     65792   1  P16  : 132.128       
     3 : ECMWF    unknown  instant       1   2     65792   1  P16  : 152.128       
   Grid coordinates :
     1 : spectral                 : points=65792  nsp=32896  truncation=255  complexPacking
   Vertical coordinates :
     1 : pressure                 : levels=1
                              lev : 85000 Pa
     2 : pressure                 : levels=1
                              lev : 100000 Pa
   Time coordinate :  unlimited steps
     RefTime =  1981-01-01 00:00:00  Units = hours  Calendar = proleptic_gregorian
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  1981-01-01 00:00:00  1981-01-01 03:00:00  1981-01-01 06:00:00  1981-01-01 12:00:00
  1981-01-01 18:00:00  1981-01-01 21:00:00  1981-01-02 00:00:00  1981-01-02 06:00:00
[...]
  1981-01-10 00:00:00  1981-01-10 03:00:00  1981-01-10 06:00:00  1981-01-10 12:00:00
  1981-01-10 18:00:00  1981-01-10 21:00:00  1981-01-11 00:00:00  1981-01-11 06:00:00
Warning (cgribexScanTimestep) : Inconsistent timestep 100 (GRIB record 1/3)!
Warning (cgribexScanTimestep) : Record 297 (id=152.128 lev1=100000 lev2=0) timestep 100: Paramameter not found!
  1981-01-11 12:00:00  1981-01-11 15:00:00  1981-01-11 18:00:00  1981-01-12 00:00:00
  1981-01-12 06:00:00  1981-01-12 09:00:00  1981-01-12 12:00:00  1981-01-12 18:00:00
[...]
  1981-01-18 06:00:00  1981-01-18 09:00:00  1981-01-18 12:00:00  1981-01-18 18:00:00
  1981-01-19 00:00:00  1981-01-19 03:00:00  1981-01-19 06:00:00
cdo sinfo: Processed 3 variables over 99 timesteps ( 0.04s )
```
Note the warning and break after day 11: the output frequency seems to shift from 6 hours to 3 hours, and the month seems to end at day 19. How can this happen?

The model output looks OK, 6-hourly output, pressure levels and lnsp, nothing peculiar.

**Comment by klauswyser** [comment]
Things are getting clearer now: I have removed the 3-hourly output of u and v on the 850 hPa level which means I don't save any 3-hourly output in the ICMSH file. Obviously I thus cannot process ua850 and va850 because they are in E3hrPt.

What puzzles me though is that filter6hr.py still tries to produce a 3hr file. Wouldn't it be possible that filter6hr.py "sees" that there are no 3-hourly data in the ICMSH output file?

**Comment by goord** [comment]
rev. 3a31cfadaa33ee646e88107e7a92d7793644ca63
