### ISSUE TITLE
Few questions to derived variables from IFS

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#87]
Some variables needed for CMIP6 are not saved driectly by IFS but can be obtained in the post-processing. `resources/ifspar.json` contains the 'recipes' for how variables are processed with the cdo expr command. When going through `ifspar.json` I found a number of expression that may need revision.

```
    {
        "source": "43.128",
        "target": "mrso",
        "expr": "var43=70*var39+210*var40+720*var41+1890*var42",
        "masked": "land"
    },
```
The deepest soil layer in IFS stretches from 100 to 255 cm, shouldn't then the last factor be 1550 instead of 1890?

```
    {
        "source": "118.128",
        "target": "mrlsl",
        "expr": "var118=merge(70*var39,210*var40,720*var41,1890*var42)",
        "masked": "land"
    },
```
Same here.
2nd question: where does variable mrlsl come from? I cannot find it in the [the data request for CMIP6](http://clipc-services.ceda.ac.uk/dreq/mipVars.html).

```
    {
        "source": "121.128",
        "target": "mrlsl",
        "table": "6hrPlevPt",
        "expr": "var118=70*var39",
        "masked": "land"
    },
```
mrlsl isn't defined for CMIP6 (see above), and it also seems we have 2 different definitions for mrlsl (var118, see above).

```
    {
        "source": "120.128",
        "target": "hfdsn",
        "expr": "var120=(var141>0)*(var146+var147)",
        "convert": "cum2inst"
    },
```
hfdsn should be "Downward Heat Flux into Snow Where Land over Land", but `var146+var147`is just the latent and sensible heat flux. Suggestion: `var120=(var141>0)*(var169+var175+var146+var147)`

```
    {
        "mask": "land",
        "expr": "var172>0.5"
    },
    {
        "mask": "sea",
        "expr": "var172<0.5"
    }
```
What if var172==0.5 in some points? One of the > or < signs should be <= or >=.

**Comment by goord** [comment]
Hi Klaus, I thought the lowest soil level stretched to 289 cm (I got that from [here](https://software.ecmwf.int/wiki/display/OIFS/How+to+control+OpenIFS+output)) but perhaps this version is only to 255 cm?

Mrlsl was the water content in the top soil layer, but it is perfectly possible that this variable has been removed from the data request in favour of tsl which has this as its first slide. If variables disappear from the data request, I usually don't remove them from this list for backward compatibility reasons.

You're correct about hfdsn, I will fix it asap.

And what about the land/sea mask boundary? I couldn't find documentation about what type of surface var172=0.5 defines... do you have an opinion about this?

**Comment by klauswyser** [comment]
> I thought the lowest soil level stretched to 289 cm (I got that from here) but perhaps this version is only to 255 cm?

It's pretty confusing, I got the 255 cm when looking at an output file with `cdo sinfo ...`. Then I went to the IFS documentation, Part 4, Table 8.6, and it says
> Depth of soil layer 4      1.89 m

Seems you are right! Why is then cdo insisting that layer 4 is 255 cm deep? The depth is coded with 8 bits in the Grib file and therefore cannot exceed 255... When inspecting the output with grib_ls instead I get 100-MISSING as the depth range of layer 4.

> And what about the land/sea mask boundary? I couldn't find documentation about what type of surface var172=0.5 defines... do you have an opinion about this?

A gridpoint with var172=0.5 must be either land or water, but cannot remain undefined. In updclie.F90 we use LSM<=0.5 to identify sea points, maybe we could use the same definition here.

**Comment by goord** [comment]
ok, will do

**Comment by klauswyser** [comment]
> hfdsn should be "Downward Heat Flux into Snow Where Land over Land", but var146+var147is just the latent and sensible heat flux. Suggestion: `var120=(var141>0)*(var169+var175+var146+var147)`

Correction: it should read `var120=(var141>0)*(var176+var177+var146+var147)` because hfdsn is "[the net downward heat flux from the atmosphere into the snow](http://clipc-services.ceda.ac.uk/dreq/u/a634ef4f4c0cda3a3c0c02652ca8cc6a.html)", and not just "downward heat flux"

**Comment by goord** [comment]
rev. d295b9180c798ac93b66b5add92b6b610a5ee202
