### ISSUE TITLE
Problem when processing sp variables

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#89]
I run into problems when processing spectral variables and have therefore reduced varlist.json to only table Emon (16 variables, 6-hr):
```
INFO:jsonloader:Found 16 cmor target variables in input variable list.
INFO:jsonloader:Created 16 ece2cmor tasks from input variable list.
INFO:ece2cmorlib:Selected 16 IFS tasks from 16 input tasks
INFO:ifs2cmor:Inspecting 16 tasks.
INFO:ifs2cmor:Validated 16 tasks for processing.
INFO:ifs2cmor:Executing 16 IFS tasks...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
Traceback (most recent call last):
  File "./ece2cmor.py", line 88, in <module>
    main(sys.argv[1:])
  File "./ece2cmor.py", line 83, in main
    maxsizegb = args.tmpsize)
  File "/home/sm_wyser/ece2cmor3/ece2cmorlib.py", line 135, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks,cleanup = cleanup)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 123, in execute
    oldsptasks,newsptasks = get_sp_tasks(supportedtasks)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 254, in get_sp_tasks
    sptask = cmor_task.cmor_task(surface_pressure,cmor_target.cmor_target("sp",freq))
  File "/home/sm_wyser/ece2cmor3/cmor_task.py", line 11, in __init__
    raise Exception("Invalid source argument type for cmor task:",type(source_))
Exception: ('Invalid source argument type for cmor task:', <type 'instance'>)
```
Any idea?

**Comment by goord** [comment]
Ah sorry this is a bug in the primavera branch! I'll fix it right away...

**Comment by goord** [comment]
Ok I committed the fix, can you try again after pulling the latest revision?

**Comment by klauswyser** [comment]
Thanks, the update helped.

I now have another (yet related) problem: I have saved only 21 pressure levels in the ICMSH file (top at 1 Pa). postproc goes fine, but the problem is then saving the cmor file:
```
Exception in thread Thread-55:
Traceback (most recent call last):
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/threading.py", line 8
01, in __bootstrap_inner
    self.run()
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/threading.py", line 7
54, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 370, in cmor_worker
    execute_netcdf_task(task)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 431, in execute_netcdf_task
    cmor_utils.netcdf2cmor(varid,ncvar,timdim,factor,storevar,get_spvar(sppath),
swaplatlon = False,fliplat = True,mask = maskarr,missval = missval)
  File "/home/sm_wyser/ece2cmor3/cmor_utils.py", line 225, in netcdf2cmor
    cmor.write(varid,vals,ntimes_passed = (0 if timdim < 0 else (imax - i)))
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/site-packages/cmor/py
wrapper.py", line 640, in write
    raise Exception,"Error: your data shape (%s) does not match the expected var
iable shape (%s)\nCheck your variable dimensions before caling cmor_write" % (st
r(osh),str(ogoodshape))
Exception: Error: your data shape ((256, 512, 11, 1)) does not match the expected v
ariable shape ([256, 512, 27, 0])
Check your variable dimensions before caling cmor_write
```
An interesting aspect is that $tmpdir/hus27_Emon.nc has only 11(!) vertical levels:
```levels    = 100000 92500 85000 70000 60000 50000 40000 30000 25000 20000 10000 ```
while ICMSH had 21 (even after the processing with filter6hr.py):
```levels    = 100000 92500 85000 70000 60000 50000 40000 30000 25000 20000 10000 7000 5000 3000 2000 1000 700 500 300 200 100```
Where did the other 10 vertical levels end up?

And where and how can I change the instruction that only 21 (not 27) pressure levels should be processed?

**Comment by goord** [comment]
Hi Klaus, ece2cmor3 reads those pressure levels from the cmip-tables, from the file CMIP6_coordinate.json. I think what happened is that it tries to select those levels from your ICMSH in the 6hr folder and only finds 10 levels. So I would change the plev27 list to those 10 levels that it can find in your data and you should be fine.

**Comment by goord** [comment]
Maybe we can make the level selection more robust by inserting missing values if levels are not found, but this will take some effort I expect.

**Comment by klauswyser** [comment]
Yes, I saw that the level selection is pretty hardcoded in the CMIP6 tables and not easy to change. Filling non-existing levels with MISS would probably be a good way to go, but requires an effort which I think isn't justified at this point. When doing the CMIP6 production runs we simply have to make sure to save the correct 27 pressure levels and we'll be fine. 

For my current problem I simply skip all variables with plev27 output, I still get monthly and daily upper air fields on a sufficeintly large number of levels.
